// This file was automatically generated.  Do not modify.

'use strict';

goog.provide('Blockly.ScratchMsgs.allLocales');

goog.require('Blockly.ScratchMsgs');


Blockly.ScratchMsgs.locales["en"] =
{
    "CONTROL_FOREVER": "while True:",
    "CONTROL_REPEAT": "for _ in range(1, %1):",
    "CONTROL_IF": "if %1:",
    "CONTROL_ELSE": "else:",
    "CONTROL_STOP": "stage.stop",
    "CONTROL_STOP_ALL": "all",
    "CONTROL_STOP_THIS": "this script",
    "CONTROL_STOP_OTHER": "other scripts in sprite",
    "CONTROL_WAIT": "stage.wait(%1)",
    "CONTROL_WAITUNTIL": "stage.wait_until(%1)",
    "CONTROL_REPEATUNTIL": "while not (%1):",
    "CONTROL_WHILE": "while %1",
    "CONTROL_FOREACH": "for each %1 in %2",
    "CONTROL_STARTASCLONE": "@event start as a clone",
    "CONTROL_CREATECLONEOF": "stage.create_clone_of(%1)",
    "CONTROL_CREATECLONEOF_MYSELF": "myself",
    "CONTROL_DELETETHISCLONE": "self.delete_this_clone()",
    "CONTROL_COUNTER": "stage.counter",
    "CONTROL_INCRCOUNTER": "stage.increment_counter()",
    "CONTROL_CLEARCOUNTER": "stage.clear_counter()",
    "CONTROL_ALLATONCE": "all at once",
    "DATA_SETVARIABLETO": "stage.set(%1, %2)",
    "DATA_CHANGEVARIABLEBY": "stage.change_by(%1, %2)",
    "DATA_SHOWVARIABLE": "stage.show_variable(%1)",
    "DATA_HIDEVARIABLE": "stage.hide_variable(%1)",
    "DATA_ADDTOLIST": "%2.append(%1)",
    "DATA_DELETEOFLIST": "%2.pop(%1)",
    "DATA_DELETEALLOFLIST": "%1.clear()",
    "DATA_INSERTATLIST": "%3.insert(%2, %1)",
    "DATA_REPLACEITEMOFLIST": "%2[%1] = %3",
    "DATA_ITEMOFLIST": "%2[%1]",
    "DATA_ITEMNUMOFLIST": "%2.index(%1)",
    "DATA_LENGTHOFLIST": "len(%1)",
    "DATA_LISTCONTAINSITEM": "%2 in %1",
    "DATA_SHOWLIST": "stage.show_list(%1)",
    "DATA_HIDELIST": "stage.hide_list(%1)",
    "DATA_INDEX_ALL": "all",
    "DATA_INDEX_LAST": "last",
    "DATA_INDEX_RANDOM": "random",
    "EVENT_WHENFLAGCLICKED": "@event when flag clicked",
    "EVENT_WHENTHISSPRITECLICKED": "@event this sprite clicked",
    "EVENT_WHENSTAGECLICKED": "@event stage clicked",
    "EVENT_WHENTOUCHINGOBJECT": "@event sprite touched %1",
    "EVENT_WHENBROADCASTRECEIVED": "@event %1 received",
    "EVENT_WHENBACKDROPSWITCHESTO": "@event backdrop switches to %1",
    "EVENT_WHENGREATERTHAN": "@event %1 > %2",
    "EVENT_WHENGREATERTHAN_TIMER": "timer",
    "EVENT_WHENGREATERTHAN_LOUDNESS": "loudness",
    "EVENT_BROADCAST": "stage.broadcast(%1)",
    "EVENT_BROADCASTANDWAIT": "stage.broadcast_and_wait(%1)",
    "EVENT_WHENKEYPRESSED": "@event %1 key pressed",
    "EVENT_WHENKEYPRESSED_SPACE": "space",
    "EVENT_WHENKEYPRESSED_LEFT": "left arrow",
    "EVENT_WHENKEYPRESSED_RIGHT": "right arrow",
    "EVENT_WHENKEYPRESSED_DOWN": "down arrow",
    "EVENT_WHENKEYPRESSED_UP": "up arrow",
    "EVENT_WHENKEYPRESSED_ANY": "any",
    "EVENT_DEFAULT_NAME": "script_name",
    "LOOKS_SAYFORSECS": "self.say_for(%1, %2)",
    "LOOKS_SAY": "self.say(%1)",
    "LOOKS_HELLO": "Hello!",
    "LOOKS_THINKFORSECS": "self.think_for(%1, %2)",
    "LOOKS_THINK": "self.think(%1)",
    "LOOKS_HMM": "Hmm...",
    "LOOKS_SHOW": "self.show()",
    "LOOKS_HIDE": "self.hide()",
    "LOOKS_HIDEALLSPRITES": "stage.hide_all_sprites()",
    "LOOKS_EFFECT_COLOR": "color",
    "LOOKS_EFFECT_FISHEYE": "fisheye",
    "LOOKS_EFFECT_WHIRL": "whirl",
    "LOOKS_EFFECT_PIXELATE": "pixelate",
    "LOOKS_EFFECT_MOSAIC": "mosaic",
    "LOOKS_EFFECT_BRIGHTNESS": "brightness",
    "LOOKS_EFFECT_GHOST": "ghost",
    "LOOKS_CHANGEEFFECTBY": "self.change_effect_by(%1, %2)",
    "LOOKS_SETEFFECTTO": "self.set_effect_to(%1, %2)",
    "LOOKS_CLEARGRAPHICEFFECTS": "self.clear_graphic_effects()",
    "LOOKS_CHANGESIZEBY": "self.change_size_by(%1)",
    "LOOKS_SETSIZETO": "self.set_size_to(%1)",
    "LOOKS_SIZE": "self.size",
    "LOOKS_CHANGESTRETCHBY": "self.change_stretch_by(%1)",
    "LOOKS_SETSTRETCHTO": "self.set_stretch_to(%1)",
    "LOOKS_SWITCHCOSTUMETO": "self.switch_costume_to(%1)",
    "LOOKS_NEXTCOSTUME": "self.next_costume()",
    "LOOKS_SWITCHBACKDROPTO": "stage.switch_backdrop_to(%1)",
    "LOOKS_GOTOFRONTBACK": "self.go_to_layer(%1)",
    "LOOKS_GOTOFRONTBACK_FRONT": "front",
    "LOOKS_GOTOFRONTBACK_BACK": "back",
    "LOOKS_GOFORWARDBACKWARDLAYERS": "self.go_layers(%1, %2)",
    "LOOKS_GOFORWARDBACKWARDLAYERS_FORWARD": "forward",
    "LOOKS_GOFORWARDBACKWARDLAYERS_BACKWARD": "backward",
    "LOOKS_BACKDROPNUMBERNAME": "stage.backdrop(%1)",
    "LOOKS_COSTUMENUMBERNAME": "self.costume(%1)",
    "LOOKS_NUMBERNAME_NUMBER": "number",
    "LOOKS_NUMBERNAME_NAME": "name",
    "LOOKS_SWITCHBACKDROPTOANDWAIT": "stage.switch_backdrop_and_wait(%1)",
    "LOOKS_NEXTBACKDROP_BLOCK": "stage.next_backdrop()",
    "LOOKS_NEXTBACKDROP": "next backdrop",
    "LOOKS_PREVIOUSBACKDROP": "previous backdrop",
    "LOOKS_RANDOMBACKDROP": "random backdrop",
    "MOTION_MOVESTEPS": "self.move_steps(%1)",
    "MOTION_TURNLEFT": "self.turn_left_degrees(%1)",
    "MOTION_TURNRIGHT": "self.turn_right_degrees(%1)",
    "MOTION_POINTINDIRECTION": "self.point_in_direction(%1)",
    "MOTION_POINTTOWARDS": "self.point_towards(%1)",
    "MOTION_POINTTOWARDS_POINTER": "mouse-pointer",
    "MOTION_POINTTOWARDS_RANDOM": "random direction",
    "MOTION_GOTO": "self.go_to(%1)",
    "MOTION_GOTO_POINTER": "mouse-pointer",
    "MOTION_GOTO_RANDOM": "random position",
    "MOTION_GOTOXY": "self.go_to_x_y(%1, %2)",
    "MOTION_GLIDESECSTOXY": "self.glide_for_secs_to_x_y(%1, %2, %3)",
    "MOTION_GLIDETO": "self.glide_for_secs_to(%1, %2)",
    "MOTION_GLIDETO_POINTER": "mouse-pointer",
    "MOTION_GLIDETO_RANDOM": "random position",
    "MOTION_CHANGEXBY": "self.change_x_by(%1)",
    "MOTION_SETX": "self.set_x_to(%1)",
    "MOTION_CHANGEYBY": "self.change_y_by(%1)",
    "MOTION_SETY": "self.set_y_to(%1)",
    "MOTION_IFONEDGEBOUNCE": "self.if_on_edge_bounce()",
    "MOTION_SETROTATIONSTYLE": "self.set_rotation_style(%1)",
    "MOTION_SETROTATIONSTYLE_LEFTRIGHT": "left-right",
    "MOTION_SETROTATIONSTYLE_DONTROTATE": "don't rotate",
    "MOTION_SETROTATIONSTYLE_ALLAROUND": "all around",
    "MOTION_XPOSITION": "self.x_position",
    "MOTION_YPOSITION": "self.y_position",
    "MOTION_DIRECTION": "self.direction",
    "MOTION_SCROLLRIGHT": "scroll right %1",
    "MOTION_SCROLLUP": "scroll up %1",
    "MOTION_ALIGNSCENE": "align scene %1",
    "MOTION_ALIGNSCENE_BOTTOMLEFT": "bottom-left",
    "MOTION_ALIGNSCENE_BOTTOMRIGHT": "bottom-right",
    "MOTION_ALIGNSCENE_MIDDLE": "middle",
    "MOTION_ALIGNSCENE_TOPLEFT": "top-left",
    "MOTION_ALIGNSCENE_TOPRIGHT": "top-right",
    "MOTION_XSCROLL": "x scroll",
    "MOTION_YSCROLL": "y scroll",
    "MOTION_STAGE_SELECTED": "Stage selected: no motion blocks",
    "OPERATORS_ADD": "%1 + %2",
    "OPERATORS_SUBTRACT": "%1 - %2",
    "OPERATORS_MULTIPLY": "%1 * %2",
    "OPERATORS_DIVIDE": "%1 / %2",
    "OPERATORS_RANDOM": "stage.random(%1, %2)",
    "OPERATORS_GT": "%1 > %2",
    "OPERATORS_LT": "%1 < %2",
    "OPERATORS_EQUALS": "%1 == %2",
    "OPERATORS_AND": "%1 and %2",
    "OPERATORS_OR": "%1 or %2",
    "OPERATORS_NOT": "not %1",
    "OPERATORS_JOIN": "stage.join(%1, %2)",
    "OPERATORS_JOIN_APPLE": "apple",
    "OPERATORS_JOIN_BANANA": "banana",
    "OPERATORS_LETTEROF": "%2[%1]",
    "OPERATORS_LETTEROF_APPLE": "a",
    "OPERATORS_LENGTH": "len(%1)",
    "OPERATORS_CONTAINS": "%2 in %1",
    "OPERATORS_MOD": "%1 % %2",
    "OPERATORS_ROUND": "stage.round(%1)",
    "OPERATORS_MATHOP": "stage.maths_op(%1, %2)",
    "OPERATORS_MATHOP_ABS": "abs",
    "OPERATORS_MATHOP_FLOOR": "floor",
    "OPERATORS_MATHOP_CEILING": "ceiling",
    "OPERATORS_MATHOP_SQRT": "sqrt",
    "OPERATORS_MATHOP_SIN": "sin",
    "OPERATORS_MATHOP_COS": "cos",
    "OPERATORS_MATHOP_TAN": "tan",
    "OPERATORS_MATHOP_ASIN": "asin",
    "OPERATORS_MATHOP_ACOS": "acos",
    "OPERATORS_MATHOP_ATAN": "atan",
    "OPERATORS_MATHOP_LN": "ln",
    "OPERATORS_MATHOP_LOG": "log",
    "OPERATORS_MATHOP_EEXP": "e ^",
    "OPERATORS_MATHOP_10EXP": "10 ^",
    "PROCEDURES_DEFINITION": "def %1:",
    "START_PROCEDURES_DEFINITION": "def %1(self):",
    "SENSING_TOUCHINGOBJECT": "self.touching(%1)",
    "SENSING_TOUCHINGOBJECT_POINTER": "mouse-pointer",
    "SENSING_TOUCHINGOBJECT_EDGE": "edge",
    "SENSING_TOUCHINGCOLOR": "self.touching_color(%1)",
    "SENSING_COLORISTOUCHINGCOLOR": "self.color_is_touching(%1, %2)",
    "SENSING_DISTANCETO": "self.distance_to(%1)",
    "SENSING_DISTANCETO_POINTER": "mouse-pointer",
    "SENSING_ASKANDWAIT": "self.ask_and_wait(%1)",
    "SENSING_ASK_TEXT": "What's your name?",
    "SENSING_ANSWER": "stage.answer",
    "SENSING_KEYPRESSED": "stage.key_pressed(%1)",
    "SENSING_MOUSEDOWN": "mouse down?",
    "SENSING_MOUSEX": "self.mouse_x",
    "SENSING_MOUSEY": "self.mouse_y",
    "SENSING_SETDRAGMODE": "self.set_drag_mode(%1)",
    "SENSING_SETDRAGMODE_DRAGGABLE": "draggable",
    "SENSING_SETDRAGMODE_NOTDRAGGABLE": "not draggable",
    "SENSING_LOUDNESS": "self.loudness",
    "SENSING_LOUD": "loud?",
    "SENSING_TIMER": "self.timer",
    "SENSING_RESETTIMER": "self.reset_timer",
    "SENSING_OF": "self.get_value(%1, %2)",
    "SENSING_OF_XPOSITION": "x position",
    "SENSING_OF_YPOSITION": "y position",
    "SENSING_OF_DIRECTION": "direction",
    "SENSING_OF_COSTUMENUMBER": "costume #",
    "SENSING_OF_COSTUMENAME": "costume name",
    "SENSING_OF_SIZE": "size",
    "SENSING_OF_VOLUME": "volume",
    "SENSING_OF_BACKDROPNUMBER": "backdrop #",
    "SENSING_OF_BACKDROPNAME": "backdrop name",
    "SENSING_OF_STAGE": "Stage",
    "SENSING_CURRENT": "stage.current(%1)",
    "SENSING_CURRENT_YEAR": "year",
    "SENSING_CURRENT_MONTH": "month",
    "SENSING_CURRENT_DATE": "date",
    "SENSING_CURRENT_DAYOFWEEK": "day of week",
    "SENSING_CURRENT_HOUR": "hour",
    "SENSING_CURRENT_MINUTE": "minute",
    "SENSING_CURRENT_SECOND": "second",
    "SENSING_DAYSSINCE2000": "self.days_since_2000()",
    "SENSING_USERNAME": "stage.username",
    "SENSING_USERID": "user id",
    "SOUND_PLAY": "stage.start_sound(%1)",
    "SOUND_PLAYUNTILDONE": "stage.play_sound_until_done(%1)",
    "SOUND_STOPALLSOUNDS": "stage.stop_all_sounds()",
    "SOUND_SETEFFECTO": "stage.set_sound_effect_to(%1, %2)",
    "SOUND_CHANGEEFFECTBY": "stage.change_sound_effect(%1. %2)",
    "SOUND_CLEAREFFECTS": "stage.clear_sound_effects()",
    "SOUND_EFFECTS_PITCH": "pitch",
    "SOUND_EFFECTS_PAN": "pan left/right",
    "SOUND_CHANGEVOLUMEBY": "stage.change_volume_by(%1)",
    "SOUND_SETVOLUMETO": "stage.set_volume_to(%1)",
    "SOUND_VOLUME": "stage.volume",
    "SOUND_RECORD": "record...",
    "CATEGORY_MOTION": "Motion",
    "CATEGORY_LOOKS": "Looks",
    "CATEGORY_SOUND": "Sound",
    "CATEGORY_EVENTS": "Events",
    "CATEGORY_CONTROL": "Control",
    "CATEGORY_SENSING": "Sensing",
    "CATEGORY_OPERATORS": "Operators",
    "CATEGORY_VARIABLES": "Variables",
    "CATEGORY_MYBLOCKS": "My Blocks",
    "DUPLICATE": "Duplicate",
    "DELETE": "Delete",
    "ADD_COMMENT": "Add Comment",
    "REMOVE_COMMENT": "Remove Comment",
    "DELETE_BLOCK": "Delete Block",
    "DELETE_X_BLOCKS": "Delete %1 Blocks",
    "DELETE_ALL_BLOCKS": "Delete all %1 blocks?",
    "CLEAN_UP": "Clean up Blocks",
    "HELP": "Help",
    "UNDO": "Undo",
    "REDO": "Redo",
    "EDIT_PROCEDURE": "Edit",
    "SHOW_PROCEDURE_DEFINITION": "Go to definition",
    "WORKSPACE_COMMENT_DEFAULT_TEXT": "Say something...",
    "COLOUR_HUE_LABEL": "Color",
    "COLOUR_SATURATION_LABEL": "Saturation",
    "COLOUR_BRIGHTNESS_LABEL": "Brightness",
    "CHANGE_VALUE_TITLE": "Change value:",
    "RENAME_VARIABLE": "Rename variable",
    "RENAME_VARIABLE_TITLE": "Rename all \"%1\" variables to:",
    "RENAME_VARIABLE_MODAL_TITLE": "Rename Variable",
    "NEW_VARIABLE": "Make a Variable",
    "NEW_VARIABLE_TITLE": "New variable name:",
    "VARIABLE_MODAL_TITLE": "New Variable",
    "VARIABLE_ALREADY_EXISTS": "A variable named \"%1\" already exists.",
    "VARIABLE_ALREADY_EXISTS_FOR_ANOTHER_TYPE": "A variable named \"%1\" already exists for another variable of type \"%2\".",
    "DELETE_VARIABLE_CONFIRMATION": "Delete %1 uses of the \"%2\" variable?",
    "CANNOT_DELETE_VARIABLE_PROCEDURE": "Can't delete the variable \"%1\" because it's part of the definition of the function \"%2\"",
    "DELETE_VARIABLE": "Delete the \"%1\" variable",
    "NEW_PROCEDURE": "Make a Block",
    "PROCEDURE_ALREADY_EXISTS": "A procedure named \"%1\" already exists.",
    "PROCEDURE_DEFAULT_NAME": "block_name",
    "NEW_LIST": "Make a List",
    "NEW_LIST_TITLE": "New list name:",
    "LIST_MODAL_TITLE": "New List",
    "LIST_ALREADY_EXISTS": "A list named \"%1\" already exists.",
    "RENAME_LIST_TITLE": "Rename all \"%1\" lists to:",
    "RENAME_LIST_MODAL_TITLE": "Rename List",
    "DEFAULT_LIST_ITEM": "thing",
    "DELETE_LIST": "Delete the \"%1\" list",
    "RENAME_LIST": "Rename list",
    "NEW_BROADCAST_MESSAGE": "New message",
    "NEW_BROADCAST_MESSAGE_TITLE": "New message name:",
    "BROADCAST_MODAL_TITLE": "New Message",
    "DEFAULT_BROADCAST_MESSAGE_NAME": "message1"
};
